---
- name: Deploy Application
  hosts: web_servers
  become: yes

  vars:
    image_name: miguelrodr1gues/user-service
    image_tag: latest
    container_name: user-service

  tasks:

    - name: Pull image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Remove old container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Run container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"