version: '3.8'

services:

  api-gateway:
    image: miguelrodr1gues/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USER_SERVICE_URL: http://user-service:8080
      PRODUCT_SERVICE_URL: http://product-service:8080
      ORDER_SERVICE_URL: http://order-service:8080
    restart: unless-stopped
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-service:
    image: miguelrodr1gues/product-service:latest
    container_name: product-service
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${RDS_ENDPOINT}:5432/cloudprojectdb"
      SPRING_DATASOURCE_USERNAME: dr1gues
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_REGION: eu-central-1
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service:
    image: miguelrodr1gues/user-service:latest
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${RDS_ENDPOINT}:5432/cloudprojectdb"
      SPRING_DATASOURCE_USERNAME: dr1gues
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_REGION: eu-central-1
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order-service:
    image: miguelrodr1gues/order-service:latest
    container_name: order-service
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${RDS_ENDPOINT}:5432/cloudprojectdb"
      SPRING_DATASOURCE_USERNAME: dr1gues
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_REGION: eu-central-1
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
